name: ElizabethP
layout_spectrum: 0.12938
typography_spectrum: 0.89358
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#bad0e8'
    - '#8b9db1'
    - '#232524'
    - '#fffffd'
    - '#ffe35d'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
title: 'Location, location, locatiin'
author:
  name: Elizabeth
  url: ''
  email: elipanetta@gmail.com
content_rating:
  adult: false
